// src/components/HighlightingTextArea.vue
<template>
  <div class="container">
    <div class="wordContainer fit">
      <div :hidden="!highlight" class="backdrop box" ref="backdrop" @scroll="onBackdropScroll">
        <mark class="highlights" v-if="highlightText !== ''">{{ highlightText }}</mark>
        <span ref="anchor" style="width: 0; height: 0"></span>
        {{ noHighlightText }}
      </div>
      <textarea
        class="textInput box"
        placeholder="Paste Text here to read."
        v-model="text"
        ref="textarea"
        @focus="e => e.target.select()"
        @scroll="onTextScroll"
        @change="newText">
      </textarea>
      <q-icon name="close" @click="clearText()" class="cursor-pointer"/>
    </div>
  </div>
</template>

<script>

export default {
  name: "HighlightingTextArea",
  props: {
    currentWord: {
      type: Number,
      required: false,
      default: 0
    },
    highlight: {
      type: Boolean,
      required: true
    },
    splitText: {
      type: Array,
      required: true
    }
  },
  emits: {
    txtUpdate: {
      type: Object
    }

  },
  computed: {
    /*splitText() {
      // return this.text.replaceAll('\n', '<br>').split(/(?=\s\S)/gm);
      // return this.text.split(/(?=\s\S)/gm);
      return this.text.split(/(?=\s\S)|(?<=[^-]-)/gm);
    },*/
    highlightText() {
      if (this.currentWord < 1) return ""
      return this.splitText.slice(0, this.currentWord + 1).reduce((x, y) => x + y)
    },
    noHighlightText() {
      if (this.currentWord >= this.splitText.length - 1 || this.splitText.length < 1) return ""
      return this.splitText.slice(this.currentWord, this.splitText.length - 1).reduce((x, y) => x + y)
    }
  },
  watch:{
    highlight(newV){
      if(newV === true){
        this.$refs.anchor.scrollIntoView({behavior: "smooth"})
        this.$refs.anchor.scroll
        console.log('scrollIntoView')
      }
    }
  },
  data() {
    return {
      text: '',
      textScrolled: false,
      currentTimeout: undefined
    }
  },
  methods: {
    newText() {
      this.$emit('txtUpdate', this.text)
    },
    clearText() {
      this.text = ""
      this.newText()
    },
    setText(t) {
      this.text = t
    },
    async onTextScroll() {
      console.log('TextScroll')
      clearTimeout(this.currentTimeout)
      this.textScrolled = true
      this.$refs.backdrop.scrollTop = this.$refs.textarea.scrollTop;
      this.$refs.backdrop.scrollLeft = this.$refs.textarea.scrollLeft;
      this.currentTimeout = setTimeout(() => this.textScrolled = false, 50)
    },
    async onBackdropScroll() {
      console.log('BackdropScroll')
      if (this.textScrolled) return
      this.$refs.textarea.scrollTop = this.$refs.backdrop.scrollTop;
      this.$refs.textarea.scrollLeft = this.$refs.backdrop.scrollLeft;
    }
  }
}


</script>

<style scoped lang="scss">

@import "src/css/quasar.variables";

.textInput {
  box-sizing: border-box;
  background: transparent;

  display: block;
  z-index: 2;
  margin: 0;
  border: 2px solid #74637f;
  border-radius: 0;
  overflow: visible;
  transition: transform 1s;

  resize: none;

  @include themify {
    color: $primary-fg;
  }
}

.highlights {
  white-space: pre-wrap;
  word-wrap: break-word;
  border-radius: 3px;
  background-color: #b4893163;

  @include themify {
    //background-color: $accent-bg;
    color: $primary-fg;
  }
}

.backdrop {
  z-index: 1;
  padding: 2px 2px 2px 2px;
  border: 2px solid #596b72;
  color: transparent;
  overflow: hidden;
  pointer-events: none;
  transition: transform 1s;
  resize: none;
  position: absolute;
  white-space: pre-wrap;
  word-wrap: break-word;
}

.progressBar {
  display: block;
  height: 3px;

  @include themify {
    background-color: $accent-bg;
  }
}

.wordContainer {
  display: block;
  position: relative;
  margin: 0;
}

.box {
  width: 100%;
  height: 300px;
}

</style>

// src/lib/HighlightingTextArea.svelte
<script>
    import { createEventDispatcher, tick } from "svelte";

    export let highlight = false;
    export let currentWord = 0;
    export let splitText = [];

    let anchor;
    let textarea;
    let backdrop;

    let highlightText;
    let noHighlightText;
    let text = "";
    let textScrolled = false;
    let currentTimeout = undefined;

    $: highlightText = computeHighlightText(currentWord, splitText);
    $: noHighlightText = computeNoHighlightText(currentWord, splitText);
    $: scrollToAnchor(highlight);

    async function scrollToAnchor(hghlght) {
        // await new Promise((resolve) => setTimeout(resolve, 10))
        // afterUpdate(() => {
        //     console.log("scrollcall");
        //     if (anchor && hghlght) {
        //         anchor.scrollIntoView();
        //     }
        // });
        await tick();

        console.log("scrollcall");
        if (anchor && hghlght) {
            anchor.scrollIntoView();
            anchor.parentNode.scrollBy(0, -50);
        }
    }

    function computeHighlightText(crntWord, spltText) {
        if (crntWord < 1) return "";
        return spltText.slice(0, crntWord + 1).reduce((x, y) => x + y);
    }
    function computeNoHighlightText(crntWord, spltText) {
        if (crntWord >= spltText.length - 1 || spltText.length < 1) return "";
        return spltText
            .slice(crntWord, spltText.length - 1)
            .reduce((x, y) => x + y);
    }
    const dispatch = createEventDispatcher();

    function onFocus(e) {
        e.target.select();
    }

    function newText() {
        dispatch("txtUpdate", text);
    }
    function clearText() {
        text = "";
        newText();
    }
    export function setText(t) {
        text = t;
    }
    async function onTextScroll() {
        // console.log("TextScroll");
        if(!backdrop || !textarea) return
        clearTimeout(currentTimeout);
        textScrolled = true;
        backdrop.scrollTop = textarea.scrollTop;
        backdrop.scrollLeft = textarea.scrollLeft;
        currentTimeout = setTimeout(() => (textScrolled = false), 50);
    }
    async function onBackdropScroll() {
        // console.log("BackdropScroll");
        if(!backdrop || !textarea) return
        if (textScrolled) return;
        textarea.scrollTop = backdrop.scrollTop;
        textarea.scrollLeft = backdrop.scrollLeft;
    }
</script>

<div class="container">
    <div class="wordContainer fit">
        {#if highlightText !== ""}
            <div
                class:hidden={!highlight}
                class="backdrop box"
                bind:this={backdrop}
                on:scroll={onBackdropScroll}
            >
                <mark class="highlights">{highlightText}</mark>
                <span
                    bind:this={anchor}
                    id="anchor"
                    style="width: 0; height: 0"
                />
                {noHighlightText}
            </div>
        {/if}
        <textarea
            placeholder="Paste Text here to read."
            spellcheck="false"
            class="textInput box border-amber"
            bind:value={text}
            bind:this={textarea}
            on:focus={onFocus}
            on:scroll={onTextScroll}
            on:change={newText}
        />
<!--        <q-icon name="close" on:click={clearText} class="cursor-pointer" />-->
    </div>
</div>

<style>
    .textInput {
        box-sizing: border-box;
        background: transparent;

        display: block;
        z-index: 2;
        margin: 0;
        border: 2px solid;
        border-radius: 0;
        overflow: visible;
        transition: transform 1s;

        resize: none;
    }

    .highlights {
        white-space: pre-wrap;
        word-wrap: break-word;
        border-radius: 3px;
        background-color: #b4893163;
        color: transparent !important;
    }

    :global(.backdrop) {
        z-index: 1;
        padding: 2px 19px 2px 2px;
        /* border: 2px solid #596b72; */
        color: transparent !important;
        overflow: hidden;
        pointer-events: none;
        transition: transform 1s;
        resize: none;
        position: absolute;
        white-space: pre-wrap;
        word-wrap: break-word;
    }

    .wordContainer {
        display: block;
        position: relative;
        margin: 0;
    }

    .box {
        width: 100%;
        height: 300px;
    }
</style>
